In [5]:
import numpy as np

def rgb_to_grays(rgb_image):
  grayscale = np.dot(rgb_image, [0.2989, 0.5870, 0.1140])
  return grayscale

rgb_image = np.array([[[255, 0, 0], [0, 255, 0], [0, 0, 255]],
                       [[255, 255, 0], [255, 0, 255], [0, 255, 255]],
                       [[127, 127, 127], [200, 200, 200], [50, 50, 50]]])

grayscale = rgb_to_grays(rgb_image)
print(grayscale)


[[ 76.2195 149.685   29.07  ]
 [225.9045 105.2895 178.755 ]
 [126.9873 199.98    49.995 ]]


In [9]:
import numpy as np

def n_data(data):
  n_data = data - np.mean(data, axis=0)
  n_data = n_data / np.std(data, axis=0)

  return n_data

data = np.array([[100, 70, 70],
                  [170, 60, 66],
                  [630, 90, 99]])

n_data = n_data(data)

print(n_data)


[[-0.85074295 -0.26726124 -0.56672007]
 [-0.55298292 -1.06904497 -0.8387457 ]
 [ 1.40372587  1.33630621  1.40546577]]


In [18]:
import numpy as np
sensor_data = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
    [[7, 8, 9],
     [10, 11, 12]]])
print(sensor_data.shape)
flat_data = sensor_data.reshape(sensor_data.shape[1], -1)
print(flat_data)
reshape_data = flat_data.reshape(-1, flat_data.shape[1] // sensor_data.shape[2])
print(reshape_data)


(2, 2, 3)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [22]:
import numpy as np
ath_data = np.array([
    [10, 12, 15, 18],
    [14, 15, 13, 16],
    [8, 9, 11, 14]])
value = ath_data[:,-1] - ath_data[:,0]
print(value)


[8 2 6]


In [ ]:
import numpy as np

def  avg_score(scores):
  n_students, n_subjects, _ = scores.shape
  valid_mark = scores != -1
  last_subjects = scores[:, -min(3, n_subjects):, :]
  valid_last_subjects = last_subjects[valid_mark[:, -min(3, n_subjects):, :]]
  avg_scores = np.mean(valid_last_subjects, axis=1)
  return avg_scores

scores = np.array([
  [[70, 80, 90], [85, 90, 95], [-1, 100, 98]],
  [[60, 75, 85], [90, 80, 75], [88, 92, 95]]])

avg = avg_score(scores)
print(avg)


In [27]:
import numpy as np

def adjust_temp(temp, arr):

  return temp + arr[:, np.newaxis]

temp = np.array([
  [10.5, 12.3, 14.7, 15.9, 17.8, 18.9, 20.3, 19.7, 17.2, 14.1, 11.3, 9.4],
  [12.1, 13.8, 15.9, 17.5, 19.1, 20.4, 21.8, 21.1, 18.6, 15.4, 12.7, 10.9],
])

arr = np.array([0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3])
arr = arr.reshape(1,12)
adjusted_temp = adjust_temp(temp, arr)
print(adjusted_temp)


[[[10.7 12.6 15.1 16.4 18.4 19.6 21.1 20.4 17.8 14.6 11.7  9.7]
  [12.3 14.1 16.3 18.  19.7 21.1 22.6 21.8 19.2 15.9 13.1 11.2]]]


In [ ]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
        'Age': [25, 30, 35, 40, 45, 50, 55],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Miami',
                 'Boston'],
        'Department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales', 'IT', 'HR']}
fil_data = [employee for employee in data.values() if employee['Age'] < 45 and 'HR' not in employee['Department']]
fil_data = [{'Name': employee['Name'], 'City': employee['City']} for employee in fil_data]



print(fil_data)


In [42]:
import pandas as pd
data = {
    "Product": ["Apples", "Bananas", "Cherries", "Dates", "Elderberries", "Flour", "Grapes"],
    "Category": ["Fruit", "Fruit", "Fruit", "Fruit", "Fruit", "Bakery", "Fruit"],
    "Price": [1.20, 0.50, 3.00, 2.50, 4.00, 1.50, 2.00],
    "Promotion": [True, False, True, True, False, True, False]
}

df = pd.DataFrame(data)
products = df[(df["Category"] == "Fruit") & (df["Price"] > df["Price"].mean()) & (~df["Promotion"])]
promotions = products["Product"].tolist()
print(promotions)


['Elderberries']


In [47]:
import pandas as pd
employee = pd.DataFrame({
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing"],
    "Manager": ["John", "Rachel", "Emily", "Rachel", "Mike"]})

project = pd.DataFrame({
    "Employee": ["Alice", "Charlie", "Eve", "David"],
    "Project": ["P1", "P3", "P2", "P4"]})
df = pd.merge(employee, project, on='Employee')
print(df[['Project', 'Department', 'Manager']])


  Project Department Manager
0      P1         HR    John
1      P3    Finance   Emily
2      P4         IT  Rachel
3      P2  Marketing    Mike


In [48]:
data = {'Department': ['Electronics', 'Electronics', 'Clothing', 'Clothing', 'Home Goods'],
        'Salesperson': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Sales': [70000, 50000, 30000, 40000, 60000]}
df = pd.DataFrame(data)
avg_sales = df.groupby('Department')['Sales'].mean()
print(avg_sales)


Department
Clothing       35000.0
Electronics    60000.0
Home Goods     60000.0
Name: Sales, dtype: float64
